# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitarias-app
  labels:
    app: unitarias-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unitarias-app
  template:
    metadata:
      labels:
        app: unitarias-app
    spec:
      containers:
      - name: unitarias-app
        image: unitarias-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
