# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: unitarias-service
spec:
  selector:
    app: unitarias-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
